var heroes = {
    "Гэндзи": {
        "role": "Штурм",
        "realName": "Гэндзи Шимада",
        "age": "35 лет",
        "occupation": "Искатель приключений",
        "base": "Непал",
        "clan": "Клан Шимада",
        "release_date": "10 ноября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "6",
        "icon": "img/294px-Гэндзи.png",
        "icons": ["img/гэндзи/1.png",
                  "img/гэндзи/2.png",
                  "img/гэндзи/3.png"
        ]
    },
    "Жнец": {
        "role": "Штурм",
        "realName": "Габриэль Рейес",
        "age": "Неизвестно",
        "occupation": "Наемник",
        "base": "Неизвестна",
        "clan": "Blackwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "250",
        "baseHealth": "250",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Жнец.png",
        "icons": ["img/жнец/1.png",
            "img/жнец/2.png",
            "img/жнец/3.png"
        ]
    },
    "Маккри": {
        "role": "Штурм",
        "realName": "Джесси Маккри",
        "age": "37 лет",
        "occupation": "Охотник за головами",
        "base": "Санта-Фе",
        "clan": "Blackwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Маккри.png",
        "icons": ["img/маккри/1.png",
            "img/маккри/2.png",
            "img/маккри/3.png"
        ]
    },
    "Солдат-76": {
        "role": "Штурм",
        "realName": "Джек Моррисон",
        "age": "Неизвестно",
        "occupation": "глава Overwatch",
        "base": "Неизвестна",
        "clan": "Overwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Солдат-76.png",
        "icons": ["img/солдат-76/1.png",
            "img/солдат-76/2.png",
            "img/солдат-76/3.png"
        ]
    },
    "Сомбра": {
        "role": "Штурм",
        "realName": "Неизвестно",
        "age": "30 лет",
        "occupation": "Хакер",
        "base": "Дорадо",
        "clan": "«Коготь»",
        "release_date": "13 ноября 2016",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "6",
        "icon": "img/294px-Сомбра.png",
        "icons": ["img/сомбра/1.png",
            "img/сомбра/2.png",
            "img/сомбра/3.png"
        ]
    },
    "Трейсер": {
        "role": "Штурм",
        "realName": "Лена Окстон",
        "age": "26 лет",
        "occupation": "Искательница приключений",
        "base": "Лондон",
        "clan": "Overwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "150",
        "baseHealth": "150",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "6",
        "icon": "img/294px-Трейсер.png",
        "icons": ["img/трейсер/1.png",
            "img/трейсер/2.png",
            "img/трейсер/3.png"
        ]
    },
    "Фарра": {
        "role": "Штурм",
        "realName": "Фария Амари",
        "age": "32 года",
        "occupation": "служба безопасности",
        "base": "Гиза",
        "clan": "Helix Security",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Фарра.png",
        "icons": ["img/фарра/1.png",
            "img/фарра/2.png",
            "img/фарра/3.png"
        ]
    },
    "Бастион": {
        "role": "Защита",
        "realName": "боевая машина E54 ",
        "age": "30 лет",
        "occupation": "Боевая машина",
        "base": "Неизвестна",
        "clan": "Отсутствует",
        "release_date": "27 октября 2015",
        "totalHealth": "300",
        "baseHealth": "200",
        "armor": "100",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Бастион.png",
        "icons": ["img/бастион/1.png",
            "img/бастион/2.png",
            "img/бастион/3.png"
        ]
    },
    "Крысавчик": {
        "role": "Защита",
        "realName": "Джеймисон Фокс",
        "age": "25 лет",
        "occupation": "Анархист",
        "base": "Джанкертаун",
        "clan": "Стервятники",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Крысавчик.png",
        "icons": ["img/крысавчик/1.png",
            "img/крысавчик/2.png",
            "img/крысавчик/3.png"
        ]
    },
    "Мэй": {
        "role": "Защита",
        "realName": "Мэй Лин Чжоу",
        "age": "31 год",
        "occupation": "Климатолог",
        "base": "Сиань",
        "clan": "Overwatch",
        "release_date": "10 ноября 2015",
        "totalHealth": "250",
        "baseHealth": "250",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Мэй.png",
        "icons": ["img/мэй/1.png",
            "img/мэй/2.png",
            "img/мэй/3.png"
        ]
    },
    "Вдова": {
        "role": "Защита",
        "realName": "Амели Лакруа",
        "age": "33 года",
        "occupation": "Убийца",
        "base": "Анси",
        "clan": "Коготь",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Роковая_вдова.png",
        "icons": ["img/вдова/1.png",
            "img/вдова/2.png",
            "img/вдова/3.png"
        ]
    },
    "Торбьорн": {
        "role": "Защита",
        "realName": "Торбьорн Линдхольм",
        "age": "57 лет",
        "occupation": "Конструктор оружия",
        "base": "Гетебор",
        "clan": "Overwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Торбьорн.png",
        "icons": ["img/торбьорн/1.png",
            "img/торбьорн/2.png",
            "img/торбьорн/3.png"
        ]
    },
    "Хандзо": {
        "role": "Защита",
        "realName": "Хандзо Шимада",
        "age": "38 лет",
        "occupation": "Наемник, убийца",
        "base": "Ханамура",
        "clan": "Клан Шимада",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Хандзо.png",
        "icons": ["img/ханзо/1.png",
            "img/ханзо/2.png",
            "img/ханзо/3.png"
        ]
    },
    "Заря": {
        "role": "Танк",
        "realName": "Александра Зарянова",
        "age": "28 лет",
        "occupation": "Военнослужащая",
        "base": "Красноярский фронт",
        "clan": "Российские силы обороны",
        "release_date": "27 октября 2015",
        "totalHealth": "400",
        "baseHealth": "200",
        "armor": "0",
        "shields": "200",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Заря.png",
        "icons": ["img/заря/1.png",
            "img/заря/2.png",
            "img/заря/3.png"
        ]
    },
    "Ориса": {
        "role": "Танк",
        "realName": "Ориса",
        "age": "1 месяц",
        "occupation": "Робот-защитник",
        "base": "Нумбани",
        "clan": "Отсутствует",
        "release_date": "21 марта 2017",
        "totalHealth": "400",
        "baseHealth": "200",
        "armor": "288",
        "shields": "0",
        "damage": "30",
        "speed": "5",
        "icon": "img/294px-Ориса.png",
        "icons": ["img/ориса/1.png",
            "img/ориса/2.png",
            "img/ориса/3.png"
        ]
    },
    "Райнхардт": {
        "role": "Танк",
        "realName": "Вильгельм Райнхардт",
        "age": "61 год",
        "occupation": "Искатель приключений",
        "base": "Штутгарт",
        "clan": "Overwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "500",
        "baseHealth": "300",
        "armor": "200",
        "shields": "0",
        "damage": "нет",
        "speed": "6",
        "icon": "img/294px-Райнхардт.png",
        "icons": ["img/райнхардт/1.png",
            "img/райнхардт/2.png",
            "img/райнхардт/3.png"
        ]
    },
    "Турбосвин": {
        "role": "Танк",
        "realName": "Мако Рутледж",
        "age": "48 лет",
        "occupation": "бандит",
        "base": "Джанкертаун",
        "clan": "Стервятники",
        "release_date": "27 октября 2015",
        "totalHealth": "600",
        "baseHealth": "600",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Турбосвин.png",
        "icons": ["img/турбосвин/1.png",
            "img/турбосвин/2.png",
            "img/турбосвин/3.png"
        ]
    },
    "Уинстон": {
        "role": "Танк",
        "realName": "Уинстон",
        "age": "29 лет",
        "occupation": "Ученый",
        "base": "«Горизонт»",
        "clan": "Overwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "500",
        "baseHealth": "400",
        "armor": "100",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Уинстон.png",
        "icons": ["img/уинстон/1.png",
            "img/уинстон/2.png",
            "img/уинстон/3.png"
        ]
    },
    "D.Va": {
        "role": "Танк",
        "realName": "Хана Сон",
        "age": "19 лет",
        "occupation": "киберспортсмен",
        "base": "Пусан",
        "clan": "корейская армия",
        "release_date": "10 ноября 2015",
        "totalHealth": "600",
        "baseHealth": "400",
        "armor": "200",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-D.Va.png",
        "icons": ["img/дива/1.png",
            "img/дива/2.png",
            "img/дива/3.png"
        ]
    },
    "Ана": {
        "role": "Поддержка",
        "realName": "Ана Амари",
        "age": "60 лет",
        "occupation": "охотница за головами",
        "base": "Каир",
        "clan": "Overwatch",
        "release_date": "19 июля 2016",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Ана.png",
        "icons": ["img/ана/1.png",
            "img/ана/2.png",
            "img/ана/3.png"
        ]
    },
    "Ангел": {
        "role": "Поддержка",
        "realName": "Ангела Циглер",
        "age": "37 лет",
        "occupation": "Полевой врач",
        "base": "Цюрих",
        "clan": "Overwatch",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Ангел.png",
        "icons": ["img/ангел/1.png",
            "img/ангел/2.png",
            "img/ангел/3.png"
        ]
    },
    "Дзеньятта": {
        "role": "Поддержка",
        "realName": "Текхарта Дзенъятта",
        "age": "20 лет",
        "occupation": "Странствующий гуру",
        "base": "Непал",
        "clan": "Шамбала",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "50",
        "armor": "0",
        "shields": "150",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Дзенъятта.png",
        "icons": ["img/дзеньятта/1.png",
            "img/дзеньятта/2.png",
            "img/дзеньятта/3.png"
        ]
    },
    "Лусио": {
        "role": "Поддержка",
        "realName": "Лусио Коррейя",
        "age": "26 лет",
        "occupation": "диджей",
        "base": "Рио-де-Жанейро",
        "clan": "отсутствует",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "200",
        "armor": "0",
        "shields": "0",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Лусио.png",
        "icons": ["img/лусио/1.png",
            "img/лусио/2.png",
            "img/лусио/3.png"
        ]
    },
    "Симметра": {
        "role": "Поддержка",
        "realName": "Сатья Вашвани",
        "age": "28 лет",
        "occupation": "Архитектор",
        "base": "Утопия",
        "clan": "Корпорация Vishkar",
        "release_date": "27 октября 2015",
        "totalHealth": "200",
        "baseHealth": "100",
        "armor": "0",
        "shields": "100",
        "damage": "30",
        "speed": "5.5",
        "icon": "img/294px-Симметра.png",
        "icons": ["img/симметра/1.png",
            "img/симметра/2.png",
            "img/симметра/3.png"
        ]
    },
};

$(document).ready(function () {
    $('.hero').click(function () {
        var hero = $(this).children('h3').text();
        $('.hero-title').text(hero);
        var heroInfo = heroes[hero];
        var props = Object.keys(heroInfo);
        for (var i = 0; i < props.length; i++)
            if (props != 'imgs' && props != 'img')
                $('#' + props[i]).text(heroInfo[props[i]]);
        $('#hero-icon').attr('src', heroInfo.icon);
        for (var i = 0; i < 3; i++) {
            $("#a-" + i).attr('src', heroInfo.icons[i]);
        }
    });

    $('#default').trigger('click');
});
